import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';

// Configure the font
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['500', '700'],
  subsets: ['latin'],
});


export const metadata = {
  title: "Mortgage Repayment Calc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
